In [1]:
import pandas as pd

In [2]:
cantidad = 1000000

In [3]:
import random

In [6]:
#Datos aleatorios
influencer = ["AnaSof", "Ricardo Milos", "El Borrego", "Paco Web", "Luperra", "Domelipa", "Arquijuve", "Lupitics"]
comentarios = ["Está horrible, me encanta", "Playa Delfines la mejor", "Vayan a CocoBongo", "CocoBongo sobrevalorado", "Apesta a pescado en la noche", "Me robé arena aunque era propiedad privada", "Hola mundo", "Vayan Boston, las mejores pizza-hamburguesas"]
tipo_post = ["foto", "video", "comentario"]

In [7]:
#Creacion del DataFrame
dfInfluencer = pd.DataFrame ({
    "influencer" : [random.choice(influencer) for _ in range(cantidad)],
    "likes": [round(random.uniform(5000,500000),2) for _ in range(cantidad)],
    "comentarios" : [random.choice(comentarios) for _ in range(cantidad)],
    "tipo_post" : [random.choice(tipo_post) for _ in range(cantidad)],
    "fecha" : [random.randint(2020,2026) for _ in range(cantidad)]
})

In [9]:
dfInfluencer.shape

(1000000, 5)

In [11]:
dfInfluencer.dtypes

influencer         str
likes          float64
comentarios        str
tipo_post          str
fecha            int64
dtype: object

In [12]:
dfInfluencer.memory_usage(deep=True)

Index               132
influencer     65626194
likes           8000000
comentarios    89505099
tipo_post      63333026
fecha           8000000
dtype: int64

In [13]:
dfInfluencer.memory_usage(deep=True).sum() /1024**2

np.float64(223.6027250289917)

In [14]:
dfInfluencer.head

<bound method NDFrame.head of            influencer      likes  \
0            Domelipa  378921.05
1       Ricardo Milos  471629.37
2              AnaSof   63511.71
3       Ricardo Milos  398118.88
4            Paco Web  403158.87
...               ...        ...
999995  Ricardo Milos  336582.48
999996         AnaSof  355025.12
999997     El Borrego  488992.05
999998       Domelipa  329750.20
999999        Luperra  223285.76

                                         comentarios   tipo_post  fecha
0                                         Hola mundo       video   2024
1                       Apesta a pescado en la noche       video   2023
2                            CocoBongo sobrevalorado       video   2025
3                          Está horrible, me encanta        foto   2025
4                            Playa Delfines la mejor       video   2021
...                                              ...         ...    ...
999995                  Apesta a pescado en la noche  comentario   2020
999996                                    Hola mundo  comentario   2023
999997  Vayan Boston, las mejores pizza-hamburguesas  comentario   2026
999998                             Vayan a CocoBongo  comentario   2021
999999                       CocoBongo sobrevalorado  comentario   2025

[1000000 rows x 5 columns]>

In [15]:
dfInfluencer.info

<bound method DataFrame.info of            influencer      likes  \
0            Domelipa  378921.05
1       Ricardo Milos  471629.37
2              AnaSof   63511.71
3       Ricardo Milos  398118.88
4            Paco Web  403158.87
...               ...        ...
999995  Ricardo Milos  336582.48
999996         AnaSof  355025.12
999997     El Borrego  488992.05
999998       Domelipa  329750.20
999999        Luperra  223285.76

                                         comentarios   tipo_post  fecha
0                                         Hola mundo       video   2024
1                       Apesta a pescado en la noche       video   2023
2                            CocoBongo sobrevalorado       video   2025
3                          Está horrible, me encanta        foto   2025
4                            Playa Delfines la mejor       video   2021
...                                              ...         ...    ...
999995                  Apesta a pescado en la noche  comentario   2020
999996                                    Hola mundo  comentario   2023
999997  Vayan Boston, las mejores pizza-hamburguesas  comentario   2026
999998                             Vayan a CocoBongo  comentario   2021
999999                       CocoBongo sobrevalorado  comentario   2025

[1000000 rows x 5 columns]>

In [16]:
dfInfluencer.describe()

                likes           fecha
count  1000000.000000  1000000.000000
mean    252619.633142     2022.999826
std     142862.113366        1.999630
min       5000.980000     2020.000000
25%     129030.162500     2021.000000
50%     252734.965000     2023.000000
75%     376229.295000     2025.000000
max     499999.330000     2026.000000

In [17]:
dfInfluencer.tail()

,influencer,likes,comentarios,tipo_post,fecha
999995,Ricardo Milos,336582.48,Apesta a pescado en la noche,comentario,2020
999996,AnaSof,355025.12,Hola mundo,comentario,2023
999997,El Borrego,488992.05,"Vayan Boston, las mejores pizza-hamburguesas",comentario,2026
999998,Domelipa,329750.20,Vayan a CocoBongo,comentario,2021
999999,Luperra,223285.76,CocoBongo sobrevalorado,comentario,2025